require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3.0

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/IndentationStyle:
  EnforcedStyle: tabs

Layout/IndentationWidth:
  Width: 1

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes
